Fermentador de Cafe: main/botones.c File Reference
botones.c File Reference
Manejo de botones físicos del sistema.
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/semphr.h"
#include "definiciones.h"
#include "botones.h"
Functions
void botones_init (void)
Inicializa los botones.
gpio_set_direction (BOTON_INICIO, GPIO_MODE_INPUT)
gpio_set_pull_mode (BOTON_INICIO, GPIO_PULLUP_ONLY)
gpio_reset_pin (BOTON_MEZCLA)
gpio_set_direction (BOTON_MEZCLA, GPIO_MODE_INPUT)
gpio_set_pull_mode (BOTON_MEZCLA, GPIO_PULLUP_ONLY)
printf ("[BOTONES] Inicio (GPIO %d) y Mezcla (GPIO %d) inicializados.\n", BOTON_INICIO, BOTON_MEZCLA)
bool boton_inicio_presionado (void)
Detecta si el botón de inicio fue presionado.
bool boton_mezcla_presionado (void)
Variables
SemaphoreHandle_t xSemaforoMezcla
Detailed Description
Manejo de botones físicos del sistema.
Definition in file botones.c.
Function Documentation
boton_inicio_presionado()
bool boton_inicio_presionado (void)
Detecta si el botón de inicio fue presionado.
Returns
true si fue presionado
Definition at line 34 of file botones.c.
{
    if (gpio_get_level(BOTON_INICIO) == 0) {
        vTaskDelay(pdMS_TO_TICKS(50));
        if (gpio_get_level(BOTON_INICIO) == 0) {
            // Esperamos a que suelte el botón para que no mande mil señales
            while(gpio_get_level(BOTON_INICIO) == 0) { vTaskDelay(pdMS_TO_TICKS(10)); }
            return true;
        }
    }
    return false;
}
References BOTON_INICIO.
Referenced by tarea_control_proceso().
boton_mezcla_presionado()
bool boton_mezcla_presionado (void)
Definition at line 46 of file botones.c.
{
    if (gpio_get_level(BOTON_MEZCLA) == 0) {
        vTaskDelay(pdMS_TO_TICKS(50));
        if (gpio_get_level(BOTON_MEZCLA) == 0) {
            // --- TUNEADO PARA REQUISITO: SEMÁFORO ---
            // Si el semáforo ya existe, lo entregamos ("Give")
            if (xSemaforoMezcla != NULL) {
                xSemaphoreGive(xSemaforoMezcla);
            }
            // Esperamos a que el operario suelte el botón
            while(gpio_get_level(BOTON_MEZCLA) == 0) { vTaskDelay(pdMS_TO_TICKS(10)); }
            return true;
        }
    }
    return false;
}
References BOTON_MEZCLA, and xSemaforoMezcla.
Referenced by tarea_control_proceso().
botones_init()
void botones_init (void)
Inicializa los botones.
References BOTON_INICIO.
Referenced by tarea_control_proceso().
gpio_reset_pin()
gpio_reset_pin (BOTON_MEZCLA)
References BOTON_MEZCLA.
Referenced by ds1302_init(), ldr_init(), and rgb_init().
gpio_set_direction() [1/2]
gpio_set_direction (BOTON_INICIO , GPIO_MODE_INPUT)
References BOTON_INICIO.
Referenced by dht_read_data(), ds1302_init(), ds1302_read_byte(), ds1302_write_byte(), ldr_init(), onewire_read_bit(), onewire_reset(), onewire_write_bit(), and rgb_init().
gpio_set_direction() [2/2]
gpio_set_direction (BOTON_MEZCLA , GPIO_MODE_INPUT)
References BOTON_MEZCLA.
gpio_set_pull_mode() [1/2]
gpio_set_pull_mode (BOTON_INICIO , GPIO_PULLUP_ONLY)
References BOTON_INICIO.
gpio_set_pull_mode() [2/2]
gpio_set_pull_mode (BOTON_MEZCLA , GPIO_PULLUP_ONLY)
References BOTON_MEZCLA.
printf()
printf (" Inicio (GPIO %d) y Mezcla (GPIO %d) inicializados.\n" [BOTONES], BOTON_INICIO , BOTON_MEZCLA)
References BOTON_INICIO, and BOTON_MEZCLA.
Referenced by app_main(), sd_init(), tarea_control_proceso(), and tarea_escritura_sd().
Variable Documentation
xSemaforoMezcla
SemaphoreHandle_t xSemaforoMezcla extern
Definition at line 47 of file main.c.
Referenced by app_main(), boton_mezcla_presionado(), and tarea_control_proceso().