var dir_5c982d53a68cdbcd421152b4020263a9 =
[
    [ "botones.c", "botones_8c.html", "botones_8c" ],
    [ "botones.h", "botones_8h.html", "botones_8h" ],
    [ "definiciones.h", "definiciones_8h.html", "definiciones_8h" ],
    [ "dht.c", "dht_8c.html", "dht_8c" ],
    [ "dht.h", "dht_8h.html", "dht_8h" ],
    [ "ds1302.c", "ds1302_8c.html", "ds1302_8c" ],
    [ "ds1302.h", "ds1302_8h.html", "ds1302_8h" ],
    [ "ds18b20.c", "ds18b20_8c.html", "ds18b20_8c" ],
    [ "ds18b20.h", "ds18b20_8h.html", "ds18b20_8h" ],
    [ "i2c_lcd.c", "i2c__lcd_8c.html", "i2c__lcd_8c" ],
    [ "i2c_lcd.h", "i2c__lcd_8h.html", "i2c__lcd_8h" ],
    [ "ldr.c", "ldr_8c.html", "ldr_8c" ],
    [ "ldr.h", "ldr_8h.html", "ldr_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "ph_sensor.c", "ph__sensor_8c.html", "ph__sensor_8c" ],
    [ "ph_sensor.h", "ph__sensor_8h.html", "ph__sensor_8h" ],
    [ "rgb_control.c", "rgb__control_8c.html", "rgb__control_8c" ],
    [ "rgb_control.h", "rgb__control_8h.html", "rgb__control_8h" ],
    [ "sd_log.c", "sd__log_8c.html", "sd__log_8c" ],
    [ "sd_log.h", "sd__log_8h.html", "sd__log_8h" ],
    [ "sensores.c", "sensores_8c.html", "sensores_8c" ],
    [ "sensores.h", "sensores_8h.html", "sensores_8h" ]
];