Fermentador de Cafe: main/ds18b20.c File Reference
ds18b20.c File Reference
Control del sensor de temperatura DS18B20 (OneWire).
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "esp_rom_sys.h"
#include "ds18b20.h"
Functions
static esp_err_t onewire_reset (int pin)
static void onewire_write_bit (int pin, int bit)
static int onewire_read_bit (int pin)
static void onewire_write_byte (int pin, uint8_t byte)
static uint8_t onewire_read_byte (int pin)
esp_err_t ds18b20_init (int gpio_num)
esp_err_t ds18b20_leer_temp (int gpio_num, float *temp)
Lee temperatura del sensor DS18B20.
Detailed Description
Control del sensor de temperatura DS18B20 (OneWire).
Definition in file ds18b20.c.
Function Documentation
ds18b20_init()
esp_err_t ds18b20_init (int gpio_num)
Definition at line 59 of file ds18b20.c.
{
    gpio_config_t io_conf = {
        .mode = GPIO_MODE_INPUT_OUTPUT_OD,
        .pull_up_en = GPIO_PULLUP_ENABLE,
        .pin_bit_mask = (1ULL << gpio_num)
    };
    return gpio_config(&io_conf);
}
Referenced by tarea_sensores().
ds18b20_leer_temp()
esp_err_t ds18b20_leer_temp (int gpio_num, float * temp)
Lee temperatura del sensor DS18B20.
Parameters
gpio_num Pin de datos
temp Valor de temperatura
Definition at line 72 of file ds18b20.c.
{
    if (onewire_reset(gpio_num) != ESP_OK) return ESP_FAIL;
    onewire_write_byte(gpio_num, 0xCC);
    onewire_write_byte(gpio_num, 0x44);
    vTaskDelay(pdMS_TO_TICKS(800));
    if (onewire_reset(gpio_num) != ESP_OK) return ESP_FAIL;
    onewire_write_byte(gpio_num, 0xCC);
    onewire_write_byte(gpio_num, 0xBE);
    uint8_t lsb = onewire_read_byte(gpio_num);
    uint8_t msb = onewire_read_byte(gpio_num);
    int16_t raw = (msb << 8) | lsb;
    *temp = (float)raw / 16.0;
    return ESP_OK;
}
References onewire_read_byte(), onewire_reset(), and onewire_write_byte().
Referenced by tarea_sensores().
onewire_read_bit()
int onewire_read_bit (int pin) static
Definition at line 37 of file ds18b20.c.
{
    int bit = 0;
    gpio_set_direction(pin, GPIO_MODE_OUTPUT);
    gpio_set_level(pin, 0);
    esp_rom_delay_us(6);
    gpio_set_direction(pin, GPIO_MODE_INPUT);
    esp_rom_delay_us(9);
    bit = gpio_get_level(pin);
    esp_rom_delay_us(55);
    return bit;
}
References gpio_set_direction().
Referenced by onewire_read_byte().
onewire_read_byte()
uint8_t onewire_read_byte (int pin) static
Definition at line 53 of file ds18b20.c.
{
    uint8_t byte = 0;
    for (int i = 0; i < 8; i++) if (onewire_read_bit(pin)) byte |= (1 << i);
    return byte;
}
References onewire_read_bit().
Referenced by ds18b20_leer_temp().
onewire_reset()
esp_err_t onewire_reset (int pin) static
Definition at line 12 of file ds18b20.c.
{
    gpio_set_direction(pin, GPIO_MODE_OUTPUT);
    gpio_set_level(pin, 0);
    esp_rom_delay_us(480);
    gpio_set_direction(pin, GPIO_MODE_INPUT);
    esp_rom_delay_us(70);
    int level = gpio_get_level(pin);
    esp_rom_delay_us(410);
    return (level == 0) ? ESP_OK : ESP_FAIL;
}
References gpio_set_direction().
Referenced by ds18b20_leer_temp().
onewire_write_bit()
void onewire_write_bit (int pin, int bit) static
Definition at line 23 of file ds18b20.c.
{
    gpio_set_direction(pin, GPIO_MODE_OUTPUT);
    gpio_set_level(pin, 0);
    if (bit) {
        esp_rom_delay_us(6);
        gpio_set_direction(pin, GPIO_MODE_INPUT);
        esp_rom_delay_us(64);
    } else {
        esp_rom_delay_us(60);
        gpio_set_direction(pin, GPIO_MODE_INPUT);
        esp_rom_delay_us(10);
    }
}
References gpio_set_direction().
Referenced by onewire_write_byte().
onewire_write_byte()
void onewire_write_byte (int pin, uint8_t byte) static
Definition at line 49 of file ds18b20.c.
{
    for (int i = 0; i < 8; i++) onewire_write_bit(pin, (byte >> i) & 1);
}
References onewire_write_bit().
Referenced by ds18b20_leer_temp().