Fermentador de Cafe: main/i2c_lcd.h File Reference
i2c_lcd.h File Reference
#include <stdint.h>
Functions
void lcd_init (void)
void lcd_send_cmd (uint8_t cmd)
void lcd_send_data (uint8_t data)
void lcd_send_string (char *str)
void lcd_put_cur (int row, int col)
void lcd_clear (void)
Function Documentation
lcd_clear()
void lcd_clear (void)
Definition at line 107 of file i2c_lcd.c.
                     {
    lcd_send_cmd(0x01);
}
References lcd_send_cmd().
Referenced by tarea_control_proceso(), and tarea_pantalla().
lcd_init()
void lcd_init (void)
Definition at line 63 of file i2c_lcd.c.
                    {
    i2c_master_bus_config_t bus_cfg = {
        .clk_source = I2C_CLK_SRC_DEFAULT,
        .i2c_port = I2C_NUM_0,
        .scl_io_num = LCD_SCL_GPIO,
        .sda_io_num = LCD_SDA_GPIO,
        .glitch_ignore_cnt = 7,
        .flags.enable_internal_pullup = true,
    };
    ESP_ERROR_CHECK(i2c_new_master_bus(&bus_cfg, &g_bus_handle));
    i2c_device_config_t dev_cfg = {
        .device_address = LCD_ADDR,
        .scl_speed_hz = 10000,
    };
    ESP_ERROR_CHECK(i2c_master_bus_add_device(g_bus_handle, &dev_cfg, &g_dev_handle));
    vTaskDelay(pdMS_TO_TICKS(50));
    // Inicialización manual (sin mutex aún porque no hay tareas corriendo)
    for(int i=0; i<6; i++) {
        lcd_send_nibble(0x03, false);
        vTaskDelay(pdMS_TO_TICKS(10));
    }
    lcd_send_nibble(0x02, false);
    vTaskDelay(pdMS_TO_TICKS(10));
    lcd_send_cmd(0x28);
    lcd_send_cmd(0x0C);
    lcd_send_cmd(0x06);
    lcd_send_cmd(0x01);
    vTaskDelay(pdMS_TO_TICKS(5));
}
References g_bus_handle, g_dev_handle, LCD_ADDR, LCD_SCL_GPIO, LCD_SDA_GPIO, lcd_send_cmd(), and lcd_send_nibble().
Referenced by tarea_pantalla().
lcd_put_cur()
void lcd_put_cur (int row, int col)
Definition at line 97 of file i2c_lcd.c.
{
    uint8_t pos = (row == 0) ? (0x80 + col) : (0xC0 + col);
    lcd_send_cmd(pos);
}
References lcd_send_cmd().
Referenced by tarea_pantalla().
lcd_send_cmd()
void lcd_send_cmd (uint8_t cmd)
Definition at line 45 of file i2c_lcd.c.
{
    // PROTECCIÓN CON MUTEX: Requisito de recurso compartido
    if (xMutexI2C != NULL && xSemaphoreTake(xMutexI2C, pdMS_TO_TICKS(500)) == pdTRUE) {
        lcd_send_byte(cmd, false);
        vTaskDelay(pdMS_TO_TICKS(2));
        xSemaphoreGive(xMutexI2C);
    }
}
References lcd_send_byte(), and xMutexI2C.
Referenced by lcd_clear(), lcd_init(), and lcd_put_cur().
lcd_send_data()
void lcd_send_data (uint8_t data)
Definition at line 54 of file i2c_lcd.c.
{
    // PROTECCIÓN CON MUTEX
    if (xMutexI2C != NULL && xSemaphoreTake(xMutexI2C, pdMS_TO_TICKS(500)) == pdTRUE) {
        lcd_send_byte(data, true);
        vTaskDelay(pdMS_TO_TICKS(1));
        xSemaphoreGive(xMutexI2C);
    }
}
References lcd_send_byte(), and xMutexI2C.
Referenced by lcd_send_string().
lcd_send_string()
void lcd_send_string (char * str)
Definition at line 102 of file i2c_lcd.c.
{
    // El mutex se maneja dentro de lcd_send_data para cada caracter
    while (*str) lcd_send_data((uint8_t)*str++);
}
References lcd_send_data().
Referenced by tarea_pantalla().