Fermentador de Cafe: main/ldr.h File Reference
ldr.h File Reference
#include "esp_err.h"
Functions
void ldr_init (int gpio_num)
int ldr_leer_estado (int gpio_num)
Function Documentation
ldr_init()
void ldr_init (int gpio_num)
Definition at line 4 of file ldr.c.
{
    gpio_reset_pin(gpio_num);
    gpio_set_direction(gpio_num, GPIO_MODE_INPUT);
}
References gpio_reset_pin(), and gpio_set_direction().
Referenced by tarea_sensores().
ldr_leer_estado()
int ldr_leer_estado (int gpio_num)
Definition at line 9 of file ldr.c.
{
    return !gpio_get_level(gpio_num);
}
Referenced by tarea_sensores().