Fermentador de Cafe: main/rgb_control.h File Reference
rgb_control.h File Reference
#include "esp_err.h"
Functions
void rgb_init (void)
void rgb_set_color (int r, int g, int b)
void color_verde (void)
void color_azul (void)
void color_amarillo (void)
void color_rojo (void)
void color_off (void)
Function Documentation
color_amarillo()
void color_amarillo (void)
Definition at line 32 of file rgb_control.c.
{ rgb_set_color(1, 1, 0); } // Rojo + Verde = Amarillo
References rgb_set_color().
Referenced by tarea_control_proceso().
color_azul()
void color_azul (void)
Definition at line 31 of file rgb_control.c.
{ rgb_set_color(0, 0, 1); }
References rgb_set_color().
Referenced by tarea_control_proceso().
color_off()
void color_off (void)
Definition at line 34 of file rgb_control.c.
{ rgb_set_color(0, 0, 0); }
References rgb_set_color().
color_rojo()
void color_rojo (void)
Definition at line 33 of file rgb_control.c.
{ rgb_set_color(1, 0, 0); }
References rgb_set_color().
Referenced by tarea_control_proceso().
color_verde()
void color_verde (void)
Definition at line 30 of file rgb_control.c.
{ rgb_set_color(0, 1, 0); }
References rgb_set_color().
Referenced by tarea_control_proceso().
rgb_init()
void rgb_init (void)
Definition at line 8 of file rgb_control.c.
                {
    gpio_reset_pin(RGB_RED_GPIO);
    gpio_reset_pin(RGB_GREEN_GPIO);
    gpio_reset_pin(RGB_BLUE_GPIO);
    gpio_set_direction(RGB_RED_GPIO, GPIO_MODE_OUTPUT);
    gpio_set_direction(RGB_GREEN_GPIO, GPIO_MODE_OUTPUT);
    gpio_set_direction(RGB_BLUE_GPIO, GPIO_MODE_OUTPUT);
    // FUERZA EL APAGADO TOTAL (Nivel 0)
    gpio_set_level(RGB_RED_GPIO, 0);
    gpio_set_level(RGB_GREEN_GPIO, 0);
    gpio_set_level(RGB_BLUE_GPIO, 0);
}
References gpio_reset_pin(), gpio_set_direction(), RGB_BLUE_GPIO, RGB_GREEN_GPIO, and RGB_RED_GPIO.
Referenced by tarea_control_proceso().
rgb_set_color()
void rgb_set_color (int r, int g, int b)
Definition at line 23 of file rgb_control.c.
{
    gpio_set_level(RGB_RED_GPIO, r);
    gpio_set_level(RGB_GREEN_GPIO, g);
    gpio_set_level(RGB_BLUE_GPIO, b);
}
References RGB_BLUE_GPIO, RGB_GREEN_GPIO, and RGB_RED_GPIO.
Referenced by color_amarillo(), color_azul(), color_off(), color_rojo(), and color_verde().